name: SonarCloud Analysis

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  sonarcloud:
    name: Run SonarCloud analysis
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: List files in the root directory (debugging)
        run: |
          ls -l /home/runner/work/summarycard-component/summarycard-component

      - name: Cache Node.js dependencies
        uses: actions/cache@v3
        with:
          path: component4/node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('component4/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies
        run: |
          cd component4
          npm install

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@v1
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
