name: SonarCloud Analysis

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  sonarcloud:
    name: Run SonarCloud analysis
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Set up JDK 17 (ensure compatibility with SonarScanner)
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'

      # Check Java version to confirm it's set up correctly
      - name: Check Java version
        run: java -version

      # Run SonarCloud scan
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@v1
        with:
          sonar-project-key: Nambeeshwaran03_summarycard-component
          sonar-organization: nambeeshwaran03
          sonar-host-url: https://sonarcloud.io
          sonar.sources: component4/src
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}


